# Generated by Django 5.1.7 on 2025-03-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automoveis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automovel',
            name='ano',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='automovel',
            name='portas',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='automovel',
            name='quilometragem',
            field=models.PositiveIntegerField(),
        ),
    ]
